### ISSUE TITLE
Changing display name in ajax_select

### ISSUE THREAD

**Issue by letiesperon** [holyketzer/activeadmin-ajax_filter#11]
Hi!
I'm not understanding how to pick the displayed attribute in an ajax_select. Is there a way to do that?
Thank you.

**Comment by holyketzer** [comment]
Hi @letiesperon 

It is always columns configured in `search_fields`, it doesn't make sense to use another columns because user should be able to see the search results and how it's matching with query user typed, so it's better to show at least all search columns to give user feedback about what were finded

**Comment by holyketzer** [comment]
Added `display_fileds` option
