### ISSUE TITLE
Related tables support

### ISSUE THREAD

**Issue by diofeher** [holyketzer/activeadmin-ajax_filter#24]
Hello! How are we supposed to handle related tables association in the search fields?

I've been able to make the search work and return the right value:

```ruby
f.input :patient, as: :ajax_select, data: {
        url: filter_admin_patients_path,
        search_fields: ['users.first_name'],
        limit: 1,
        ordering: []
      }
```

But when rendering, the JSON will be in a different format of the search field, like:
```json
{"id": 1, "user": {"first_name": "Test", "last_name": "Last"}}
```
and the expected name of the field is `users.first_name`, so the results are not rendered in the box.

How are we supposed to do this?

**Comment by joelrojo** [comment]
Tried a few solutions to no avail.

Closest I could get was adding `display_fields: [:modelassociation_attribute]` and then overriding the model's `to_json` so that the filter query would have that included in the response.

```ruby
  def as_json(*)
    super.tap do |hash|
      hash["associatedmodel_attribute"] = self.associatedmodel.attribute
    end
  end
```

It almost works, but for some reason the dropdown won't populate with new data that is returned from the json response.

@holyketzer Any ideas?

**Comment by holyketzer** [comment]
@joelrojo 
If  you see the expected JSON result in response, but it isn't rendered in UI  then the issue is somewhere in `selectize` gem, I faced similar cases and tried to debug but didn't have luck, also https://github.com/holyketzer/activeadmin-ajax_filter/issues/39 can be related to issues in `selectize` or way I use it.

I will try to reproduce this issue

**Comment by joelrojo** [comment]
@holyketzer thanks for the quick response! I'll look into selectize then and see what I can uncover 🙌🏽

**Comment by holyketzer** [comment]
This works for me:

```ruby
f.input :pipeline, as: :ajax_select, collection: [], data: {
  display_fields: ['uid', 'experiment_sessions.uid'],
  search_fields: ['uid'],
  ransack: 'experiment_session_uid_or_uid_cont',
  url: :filter_admin_pipelines_path
}

# and 
# Pipeline model
def as_json(*)
  super.tap do |res|
    res["experiment_sessions.uid"] = self.experiment_session.uid
  end
end
```

it searches by `uid` or related table `experiment_session.uid`, the key here is a manual ransack overriding with `ransack` option.

**Comment by joelrojo** [comment]
@holyketzer Got it to work!

The ransack line wasn't necessary for me, but the key was to include any field of the original model as the first item in `search_fields`, as you did with `uid` in your example.

Thanks for the help!
